// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"file_server/file/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload/bin",
				Handler: binFileUploadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/file"),
	)
}
